### ISSUE TITLE
Do FAT resize with fatresize utility instead of libparted

### ISSUE THREAD

**Issue by pothos** [storaged-project/libblockdev#265]
Often the resize operation will refuse to work because of errors like "GNU Parted cannot resize this partition to this size.  We are working on it!" or "Failed to read the filesystem". Meanwhile fatresize will just do the job.

**Comment by vojtechtrefny** [comment]
Fatresize is using libparted to do the resize. But thanks to that we now know it is possible to do it right, so it might be better to check fatresize code and try to fix our code.

**Comment by vpodzime** [comment]
We believe #268 fixed this.

**Comment by vojtechtrefny** [comment]
The "GNU Parted cannot resize this partition to this size. We are working on it!" is caused by resizing FAT32 under 60 MiB -- parted converts the filesystem to FAT16 to do this but it can't convert it back to FAT32 when trying to resize it back to its original size. I got the same error when using the `fatresize` utility.
