### ISSUE TITLE
Add more tests for runtime dependency checking

### ISSUE THREAD

**Issue by vpodzime** [storaged-project/libblockdev#280]
A mechanism introduced in #277, but with a small test coverage. We should ideally cover all the functions that have some dependencies and add unit tests for the internal ``check_deps()`` function.

**Comment by vojtechtrefny** [comment]
We now have dependency tests for all filesystems (https://github.com/storaged-project/libblockdev/commit/7fc372ad7aa82eb4d3f79246d8cd1ed01b7fe235) so that should cover the dependencies functionality quite nicely. Having a unit test for `check_deps` and other similar functions would be nice, but we unfortunately don't have capacity to add a new C-based test suite, so I am closing this as "sorry, but WONTFIX".
