### ISSUE TITLE
bd_fs_resize should call e2fsck before resize2fs

### ISSUE THREAD

**Issue by mvollmer** [storaged-project/libblockdev#312]
Resize2fs sometimes refuses to do the resize otherwise.  This seems to happen when the filesystem was mounted earlier but is now unmounted.  fsadm also calls e2fsck before resize2fs.

**Comment by pothos** [comment]
Hello,
in GNOME Disks the repair operation is invoked explicitly because other filesystems also require this (except it is an online resize, where it of course must not be done). Can Cockpit do the same or will every resize function be changed for consistency so that in the end it will not run twice in a row for Ext4?

**Comment by mvollmer** [comment]
> in GNOME Disks the repair operation is invoked explicitly because other filesystems also require this 

Hmm, this forces all clients to have some "expert domain knowledge".  I don't think this is ideal, but of course possible. Let's document this clearly, at least.

> Can Cockpit do the same or will every resize function be changed for consistency so that in the end it will not run twice in a row for Ext4?

Cockpit can certainly call `Check` before `Resize`.  Should that be done unconditionally, or only for some filesystems?  Which?

**Comment by vpodzime** [comment]
> Hmm, this forces all clients to have some "expert domain knowledge". I don't think this is ideal, but of course possible. Let's document this clearly, at least.

The problem here is that, AFAIK, the file systems themselves don't specify this clearly and don't provide any documentation for this. And given the fact that the check can take the same time as the resize itself or even more, I don't think it should be run implicitly here in libblockdev.
 

> Cockpit can certainly call Check before Resize. Should that be done unconditionally, or only for some filesystems? Which?

I think UDisks should provide an option in ``Resize()`` that would determine if ``Check()`` should be run before the resize or not.

**Comment by mvollmer** [comment]
> I think UDisks should provide an option in Resize() that would determine if Check() should be run before the resize or not.

I think the option should be specified as "run fsck before resize, but only if necessary" and the default should be "true".

**Comment by pothos** [comment]
Calling `Check` is not enough for e.g. NTFS because the dirty marker can be still present even if the filesystem is reported as undamaged. `Repair` also resets this marker.

**Comment by mvollmer** [comment]
> Calling Check is not enough for e.g. NTFS because the dirty marker can be still present even if the filesystem is reported as undamaged. Repair also resets this marker.

See?  I don't want to code all this into Cockpit.

**Comment by vpodzime** [comment]
> See? I don't want to code all this into Cockpit.

Yes, this definitely needs to go to some common place. I'm not against adding a function to *libblockdev* that would provide such information/hint. I UDisks and whoever else could then use that information to do what it wants/needs.

**Comment by pothos** [comment]
I like the idea of placing the repair operation inside each bd-resize function. If done consistently it reduces a lot of callback code in Disks. And because it would be done there per each function it can be left out if not needed or harmful (when ext4 is mounted). I think XFS does not need it at all. But NTFS is fun again because it needs the repair after resizing again or is elsewise marked as damaged, anyway doing so is I think good practice for other filesystems like ext4 or FAT and done by e.g. GParted.

They are two different actions, but go along anyway and in the cases where e2fsck is called manually before resizing then maybe it's not a too high burden if it is run again here - how long does it usually run if started a second time? Doing this in libbd makes more sense than in UDisks which uses the generic resize function.

**Comment by vpodzime** [comment]
> They are two different actions, but go along anyway and in the cases where e2fsck is called manually before resizing then maybe it's not a too high burden if it is run again here - how long does it usually run if started a second time?

It doesn't really matter if it is run first or second time. See https://github.com/storaged-project/libblockdev/blob/master/src/plugins/fs/ext.c#L243 for details. The thing is that we have to use the ``-f`` option because without it the check may be skipped and leaving some flags (un)set. And the check can take a really long time, for multi-TiB HDDs it can be hours.

**Comment by vpodzime** [comment]
> Doing this in libbd makes more sense than in UDisks which uses the generic resize function.

UDisks knows which file system (type) it is resizing and can run the checks/repairs/whatever based on that info. Also, that's part of the benefits of using a higher-level API (UDisks) instead of a low-level API (libblockdev).
