### ISSUE TITLE
Please review use of NULL GError**

### ISSUE THREAD

**Issue by tbzatek** [storaged-project/libblockdev#527]
Just came across another segfault leading from a `NULL` error passed in `libblockdev` calls: `bd_vdo_info()` specifically leading to NULL pointer dereference in `_utils_exec_and_report_progress()`.

While I remember the general guideline for `libblockdev` being a _always pass non-NULL error_, I think this should be also guarded by `g_warn_if_fail (error != NULL)` in functions that dereference it. Or, make `libblockdev` safe with `NULL` error everywhere. 

In any case this is a difference from general GLib guidelines and it should be noted on a visible place.

**Comment by vojtechtrefny** [comment]
I think we should allow passing `NULL` instead of error for our functions. It sometimes wouldn't make a lot of sense but it would definitely be easier and safer for our users.

**Comment by vojtechtrefny** [comment]
So we now have two options:

1. Force our users to always provide us non-`NULL` GError. That's basically what we do right now, but is a little problematic because some functions can work just fine without the error set and some will crash when trying to dereference it. If we decided to keep doing this, we probably should force this during compilation by using the [nonnull attribute](https://gcc.gnu.org/onlinedocs/gcc-3.4.3/gcc/Function-Attributes.html).

2. Allow NULL instead of errors. This is what GLib does and it is part of the [Rules for use of GError](https://developer.gnome.org/glib/stable/glib-Error-Reporting.html). We could simply log error instead of returning it and make sure we don't dereference it in our code. The problem here are some of our functions that return gboolean and `FALSE` could mean both error and valid result, for example `bd_fs_is_mountpoint` where `FALSE` could mean both "not a mountpoint" and "error when checking". For these function we'd need to:
  
      - Add another output argument or
      - change the return type to int to be able distinguish between true, false and error (-1) or
      - still force users to create GErrror if they want to be able to tell difference between "false" and "false with error".

Thoughts @vpodzime @tbzatek

**Comment by vpodzime** [comment]
I vote for the option 2. And regarding the functions where it would be ambiguous, I don't care. It's the callee's responsibility to pass non-`NULL` `GError **` if they want to know if there was an error in those functions. IIRC, the documentation of these functions mentions that `FALSE` is returned in multiple cases and `GError **error` should be use to tell the difference. If they code that calls these functions doesn't care, that's their problem, not ours.

**Comment by tbzatek** [comment]
Yes, that sounds reasonable but really depends on the API design. I.e. for functions where only _TRUE_ result is interesting for the code, it doesn't really matter whether _FALSE_ means failure or a valid state.

Would be good to find out how many such functions _libblockdev_ provides and how important ignoring failure is for the callers.

**Comment by vojtechtrefny** [comment]
These should be all functions with the error "problem". And it actually isn't that bad.

`bd_fs_can_resize/check/repair...` -- false with error means "filesystem xyz not supported" so it just adds a reason for returning false, but false still means we don't support resize/check/repair

`bd_lvm_is_supported_pe_size`, `bd_lvm_is_valid_thpool_md_size`, `bd_lvm_is_valid_thpool_chunk_size` -- these three have error argument but we are not using it.

`bd_<plugin>_is_tech_avail` -- I think these are also "ok", if we fail to check for dependency and return error, from our POW it still means the tech is not supported, because we can't even check for its availability.

So this leaves us with six "problematic" functions:
`bd_fs_is_mountpoint`
`bd_crypto_device_is_luks`
`bd_crypto_device_seems_encrypted`
`bd_swap_swapstatus`
`bd_loop_get_autoclear`
`bd_dm_map_exists`

**Comment by tbzatek** [comment]
I would personally vote for option 2., however the option 3. doesn't sound too bad either.

`gboolean bd_fs_is_mountpoint (const gchar *path, gboolean *out_is_mountpoint, GError **error)` ?
vs.
`gint bd_fs_is_mountpoint (const gchar *path, GError **error)`

**Comment by vpodzime** [comment]
I still vote for option 1. Using `gint` would require documenting the return values and `if (bd_crypto_device_is_luks())` would be a broken code because `bool(-1)` is `TRUE`. I think the functions that have `is` in their names should return boolean values.

**Comment by tbzatek** [comment]
Looks like @vojtechtrefny will act as a quorum :-) Alas, don't offer any choices next time!

**Comment by vojtechtrefny** [comment]
Ok, so the final decision is to do nothing. We can revisit this before the 3.0 release, but I think this is probably the best option.
